server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.henu.wechat.entity



#showSql
logging:
  level:
    com.henu.wechat.dao: debug